# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Treasure Hunt

# Instructions
instructions_title: How It Works
instructions: Find the post-it notes based on the clues. Go to the this domain /{word} to get the next clue.

# Permalinks
starting_permalink: first
ending_permalink: congratulations

# Congratulations page
congratulations_image: https://media.giphy.com/media/qDWSxfium1oRO/giphy.gif
congratulations_text: You've completed the treasure hunt - you can collect your prize!

# URLS
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
